import { lightTheme, darkTheme } from 'amazon-chime-sdk-component-library-react';

const { colors: lightThemeColors, shadows: lightThemeShadows } = lightTheme;
const { colors: darkThemeColors, shadows: darkThemeShadows } = darkTheme;

// Configurações de cores do Material Design (adaptadas e expandidas)
const materialColors = {
  primary: '#003543',
  secondary: '#006C4A',
  error: '#B71752',
  success: '#006C4A',
  tertiary: '#795900',
  onPrimary: '#FFFFFF',
  onSecondary: '#FFFFFF',
  onError: '#FFFFFF',
  onSurface: 'rgba(0, 0, 0, 0.87)',
  surface: '#FFFFFF',
  surface1: '#F1F4F9',
  surface2: '#EBEEF3',
  surface3: '#E5E8ED',
  surface4: '#E5E8ED',
  surface5: '#E0E3E8',
  surfaceDark: '#0B0F12',
  surfaceDark1: '#181C20',
  surfaceDark2: '#1C2024',
  surfaceDark3: '#262A2E',
  surfaceDark4: '#313539',
  // Gama completa de cores neutras
  neutral50: '#F4F0EF',
  neutral100: '#E5E2E1',
  neutral200: '#C9C6C5',
  neutral300: '#B0B0B0',
  neutral400: '#969696',
  neutral500: '#7D7D7D',
  neutral600: '#646464',
  neutral700: '#4A4A4A',
  neutral800: '#303030',
  neutral900: '#181818',
};

// Tema de chat para o modo claro
const chatLightTheme = {
  title: materialColors.onSurface,
  primaryText: materialColors.onSurface,
  secondaryText: materialColors.neutral200,
  headerBorder: materialColors.neutral50,
  containerBorder: materialColors.neutral100,
  bgd: materialColors.surface,
  fgd: materialColors.surface1,
  shadow: 'none',
  maxWidth: '18.5rem',
};

// Tema de chat para o modo escuro
const chatDarkTheme = {
  title: materialColors.onPrimary,
  primaryText: materialColors.onPrimary,
  secondaryText: materialColors.neutral50,
  headerBorder: materialColors.surfaceDark1,
  containerBorder: materialColors.surfaceDark2,
  bgd: materialColors.surfaceDark,
  fgd: materialColors.surfaceDark1,
  shadow: darkThemeShadows.none,
  maxWidth: '18.5rem',
};

// Tema claro sobrescrito com cores do Material Design
export const demoLightTheme = {
  ...lightTheme,
  fonts: {
    ...lightTheme.fonts,
    body: 'Syne, sans-serif',
  },
  colors: {
    ...lightThemeColors,
    primary: {
      ...lightThemeColors.primary,
      main: materialColors.primary,
      light: '#6AB5D0',
      dark: '#001F28',
    },
    secondary: {
      ...lightThemeColors.secondary,
      main: materialColors.secondary,
      light: '#66BC94',
      dark: '#003825',
    },
    error: {
      ...lightThemeColors.error,
      primary: materialColors.error,
      light: '#FF85A1',
      dark: '#660029',
    },
    success: {
      ...lightThemeColors.success,
      primary: materialColors.success,
      light: '#66BC94',
      dark: '#003825',
    },
    tertiary: {
      main: materialColors.tertiary,
      light: '#CEA64D',
      dark: '#402D00',
    },
    greys: {
      white: '#FFFFFF',
      grey10: materialColors.surface,
      grey20: materialColors.neutral50,
      grey30: materialColors.neutral100,
      grey40: materialColors.neutral200,
      grey50: materialColors.neutral300,
      grey60: materialColors.neutral400,
      grey70: materialColors.neutral500,
      grey80: materialColors.neutral600,
      grey90: materialColors.neutral700,
      grey100: materialColors.neutral800,
      black: materialColors.neutral900,
    },
  },
  globalStyle: {
    ...lightTheme.globalStyle,
    bgd: materialColors.surface,
    text: materialColors.onSurface,
    fontSize: lightTheme.globalStyle.fontSize,
  },
  buttons: {
    ...lightTheme.buttons,
    primary: {
      ...lightTheme.buttons.primary,
      static: {
        bgd: materialColors.primary,
        border: materialColors.primary,
        text: materialColors.onPrimary,
        shadow: lightTheme.buttons.primary.shadow,
      },
      hover: {
        bgd: '#4E9AB4',
        border: '#4E9AB4',
        text: materialColors.onPrimary,
        shadow: lightTheme.buttons.primary.shadow,
      },
      focus: {
        bgd: '#2F8099',
        border: '#2F8099',
        text: materialColors.onPrimary,
        shadow: lightTheme.buttons.primary.shadow,
      },
      active: {
        bgd: materialColors.primary,
        border: materialColors.primary,
        text: materialColors.onPrimary,
        shadow: lightTheme.buttons.primary.shadow,
      },
      selected: {
        bgd: '#00677F',
        border: '#00677F',
        text: materialColors.onPrimary,
        shadow: lightTheme.buttons.primary.shadow,
      },
      disabled: {
        bgd: materialColors.neutral100,
        border: materialColors.neutral100,
        text: materialColors.neutral200,
        shadow: lightTheme.buttons.primary.shadow,
      },
    },
    secondary: {
      ...lightTheme.buttons.secondary,
      static: {
        bgd: materialColors.secondary,
        border: materialColors.secondary,
        text: materialColors.onSecondary,
        shadow: lightTheme.buttons.secondary.shadow,
      },
      hover: {
        bgd: '#4AA07A',
        border: '#4AA07A',
        text: materialColors.onSecondary,
        shadow: lightTheme.buttons.secondary.shadow,
      },
      focus: {
        bgd: materialColors.secondary,
        border: materialColors.secondary,
        text: materialColors.onSecondary,
        shadow: lightTheme.buttons.secondary.shadow,
      },
      active: {
        bgd: materialColors.secondary,
        border: materialColors.secondary,
        text: materialColors.onSecondary,
        shadow: lightTheme.buttons.secondary.shadow,
      },
      selected: {
        bgd: '#00677F',
        border: '#00677F',
        text: materialColors.onSecondary,
        shadow: lightTheme.buttons.secondary.shadow,
      },
      disabled: {
        bgd: materialColors.neutral100,
        border: materialColors.neutral100,
        text: materialColors.neutral200,
        shadow: lightTheme.buttons.secondary.shadow,
      },
    },
  },
  inputs: {
    ...lightTheme.inputs,
    bgd: materialColors.surface1,
    border: materialColors.neutral100,
    fontColor: materialColors.onSurface,
    focus: {
      bgd: materialColors.surface2,
      border: materialColors.primary,
      shadow: lightTheme.inputs.shadow,
    },
    error: {
      border: materialColors.error,
      fontColor: materialColors.error,
      shadow: lightTheme.inputs.shadow,
    },
  },
  "shadows": {
    "none": "none",
    "small": "",
    "medium": "",
    "large": "none"
  },
  modal: {
    ...lightTheme.modal,
    title: materialColors.onSurface,
    primaryText: materialColors.onSurface,
    secondaryText: materialColors.neutral200,
    headerBorder: materialColors.neutral50,
    containerBorder: materialColors.neutral100,
    bgd: materialColors.surface,
    fgd: materialColors.surface1,
    shadow: lightThemeShadows.none,
  },
  roster: {
    ...lightTheme.roster,
    title: materialColors.onSurface,
    primaryText: materialColors.onSurface,
    secondaryText: materialColors.neutral200,
    headerBorder: materialColors.neutral50,
    containerBorder: materialColors.neutral100,
    bgd: materialColors.surface,
    fgd: materialColors.surface1,
    shadow: lightThemeShadows.none,
  },
  controlBar: {
    ...lightTheme.controlBar,
    title: materialColors.onSurface,
    primaryText: materialColors.onSurface,
    secondaryText: materialColors.neutral200,
    headerBorder: materialColors.neutral50,
    containerBorder: materialColors.neutral100,
    bgd: materialColors.surface1,
    fgd: materialColors.surface2,
    shadow: '0px 2px 4px 2px #001F2826, 0px 1px 2px 0px #001F2833',
  },
  navbar: {
    ...lightTheme.navbar,
    title: materialColors.onSurface,
    primaryText: materialColors.onSurface,
    secondaryText: materialColors.neutral200,
    headerBorder: materialColors.neutral50,
    containerBorder: materialColors.neutral100,
    bgd: materialColors.surface,
    fgd: materialColors.surface1,
    shadow: lightThemeShadows.none,
  },
  chat: chatLightTheme,
};

// Tema escuro sobrescrito com cores do Material Design
export const demoDarkTheme = {
  ...darkTheme,
  fonts: {
    ...darkTheme.fonts,
    body: 'Syne, sans-serif',
  },
  colors: {
    ...darkThemeColors,
    primary: {
      ...darkThemeColors.primary,
      main: materialColors.primary,
      light: '#6AB5D0',
      dark: '#001F28',
    },
    secondary: {
      ...darkThemeColors.secondary,
      main: materialColors.secondary,
      light: '#66BC94',
      dark: '#003825',
    },
    error: {
      ...darkThemeColors.error,
      primary: materialColors.error,
      light: '#FF85A1',
      dark: '#660029',
    },
    success: {
      ...darkThemeColors.success,
      primary: materialColors.success,
      light: '#66BC94',
      dark: '#003825',
    },
    tertiary: {
      main: materialColors.tertiary,
      light: '#CEA64D',
      dark: '#402D00',
    },
    greys: {
      black: materialColors.neutral900,
      grey100: materialColors.neutral800,
      grey90: materialColors.neutral700,
      grey80: materialColors.neutral600,
      grey70: materialColors.neutral500,
      grey60: materialColors.neutral400,
      grey50: materialColors.neutral300,
      grey40: materialColors.neutral200,
      grey30: materialColors.neutral100,
      grey20: materialColors.neutral50,
      grey10: materialColors.surface,
      white: '#FFFFFF',
    },
  },
  globalStyle: {
    ...darkTheme.globalStyle,
    bgd: materialColors.surfaceDark,
    text: materialColors.onPrimary,
    fontSize: darkTheme.globalStyle.fontSize,
  },
  buttons: {
    ...darkTheme.buttons,
    primary: {
      ...darkTheme.buttons.primary,
      static: {
        bgd: materialColors.primary,
        border: materialColors.primary,
        text: materialColors.onPrimary,
        shadow: darkTheme.buttons.primary.shadow,
      },
      hover: {
        bgd: '#4E9AB4',
        border: '#4E9AB4',
        text: materialColors.onPrimary,
        shadow: darkTheme.buttons.primary.shadow,
      },
      focus: {
        bgd: '#2F8099',
        border: '#2F8099',
        text: materialColors.onPrimary,
        shadow: darkTheme.buttons.primary.shadow,
      },
      active: {
        bgd: materialColors.primary,
        border: materialColors.primary,
        text: materialColors.onPrimary,
        shadow: darkTheme.buttons.primary.shadow,
      },
      selected: {
        bgd: '#00677F',
        border: '#00677F',
        text: materialColors.onPrimary,
        shadow: darkTheme.buttons.primary.shadow,
      },
      disabled: {
        bgd: materialColors.surfaceDark1,
        border: materialColors.surfaceDark1,
        text: materialColors.neutral50,
        shadow: darkTheme.buttons.primary.shadow,
      },
    },
    secondary: {
      ...darkTheme.buttons.secondary,
      static: {
        bgd: materialColors.secondary,
        border: materialColors.secondary,
        text: materialColors.onSecondary,
        shadow: darkTheme.buttons.secondary.shadow,
      },
      hover: {
        bgd: '#4AA07A',
        border: '#4AA07A',
        text: materialColors.onSecondary,
        shadow: darkTheme.buttons.secondary.shadow,
      },
      focus: {
        bgd: materialColors.secondary,
        border: materialColors.secondary,
        text: materialColors.onSecondary,
        shadow: darkTheme.buttons.secondary.shadow,
      },
      active: {
        bgd: materialColors.secondary,
        border: materialColors.secondary,
        text: materialColors.onSecondary,
        shadow: darkTheme.buttons.secondary.shadow,
      },
      selected: {
        bgd: '#00677F',
        border: '#00677F',
        text: materialColors.onSecondary,
        shadow: darkTheme.buttons.secondary.shadow,
      },
      disabled: {
        bgd: materialColors.surfaceDark1,
        border: materialColors.surfaceDark1,
        text: materialColors.neutral50,
        shadow: darkTheme.buttons.secondary.shadow,
      },
    },
  },
  inputs: {
    ...darkTheme.inputs,
    bgd: materialColors.surfaceDark3,
    border: materialColors.surfaceDark4,
    fontColor: materialColors.onPrimary,
    focus: {
      bgd: materialColors.surfaceDark4,
      border: materialColors.primary,
      shadow: darkTheme.inputs.shadow,
    },
    error: {
      border: materialColors.error,
      fontColor: materialColors.error,
      shadow: darkTheme.inputs.shadow,
    },
  },
  modal: {
    ...darkTheme.modal,
    bgd: materialColors.surfaceDark,
    text: materialColors.onPrimary,
    wrapperBgd: materialColors.surfaceDark,
    shadow: darkTheme.modal.shadow,
    border: materialColors.surfaceDark2,
  },
  roster: {
    ...darkTheme.roster,
    primaryText: materialColors.onPrimary,
    secondaryText: materialColors.neutral50,
    headerBorder: materialColors.surfaceDark1,
    containerBorder: materialColors.surfaceDark2,
    shadow: darkThemeShadows.none,
    bgd: materialColors.surfaceDark,
    fgd: materialColors.surfaceDark1,
    text: materialColors.onPrimary,
  },
  controlBar: {
    ...darkTheme.controlBar,
    primaryText: materialColors.onPrimary,
    secondaryText: materialColors.neutral50,
    headerBorder: materialColors.surfaceDark1,
    containerBorder: materialColors.surfaceDark2,
    shadow: darkThemeShadows.none,
    bgd: materialColors.surfaceDark,
    fgd: materialColors.surfaceDark1,
    text: materialColors.onPrimary,
  },
  navbar: {
    ...darkTheme.navbar,
    bgd: materialColors.surfaceDark,
    primaryText: materialColors.onPrimary,
    secondaryText: materialColors.neutral50,
    headerBorder: materialColors.surfaceDark1,
    containerBorder: materialColors.surfaceDark2,
    shadow: darkThemeShadows.none,
    fgd: materialColors.surfaceDark1,
    text: materialColors.onPrimary,
  },
  chat: chatDarkTheme,
};

console.log('theme', demoDarkTheme);